# This docker-compose file starts external infrastructure needed
# for local development.

version: '2'
services:
  postgresql:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/data/pgdata
    volumes:
      - ./db:/data
    ports:
      - "5432:5432"
